In [77]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv('pandas-intro.csv')

In [79]:
df_org = df.copy()

In [80]:
df.drop

<bound method DataFrame.drop of      Unnamed: 0   id first_name last_name         dob  weight  height  course  \
0             0  100    Samarth      Kari  1997-05-28      72     174     NaN   
1             1  101      Sumer       NaN  2000-06-03      62     167      DA   
2             2  102       Anay       NaN  2004-11-24      79     175     NaN   
3             3  103      Shlok       NaN  1998-12-07      62     164     NaN   
4             4  104    Anahita       NaN  1999-01-03      74     170      DA   
..          ...  ...        ...       ...         ...     ...     ...     ...   
96           96  196    Aaryahi     Baral  2001-07-05      70     165      DA   
97           97  197      Jivin       NaN  2005-10-27      70     159     NaN   
98           98  198      Rasha      Kata  1998-08-18      65     160      ML   
99           99  199      Anika       NaN  1999-12-26      75     171      DS   
100         100  200     Miraan     Varty  2002-09-04      74     163  Python

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  101 non-null    int64 
 1   id          101 non-null    int64 
 2   first_name  101 non-null    object
 3   last_name   47 non-null     object
 4   dob         101 non-null    object
 5   weight      101 non-null    int64 
 6   height      101 non-null    int64 
 7   course      75 non-null     object
 8   state       80 non-null     object
 9   marks       101 non-null    int64 
dtypes: int64(5), object(5)
memory usage: 8.0+ KB


In [82]:
df.describe(include='all')


Unnamed: 0          id first_name last_name         dob      weight  \
count   101.000000  101.000000        101        47         101  101.000000   
unique         NaN         NaN         78        47          99         NaN   
top            NaN         NaN     Kartik      Kari  1997-03-14         NaN   
freq           NaN         NaN          4         1           2         NaN   
mean     50.000000  150.000000        NaN       NaN         NaN   69.504950   
std      29.300171   29.300171        NaN       NaN         NaN    5.859392   
min       0.000000  100.000000        NaN       NaN         NaN   60.000000   
25%      25.000000  125.000000        NaN       NaN         NaN   65.000000   
50%      50.000000  150.000000        NaN       NaN         NaN   70.000000   
75%      75.000000  175.000000        NaN       NaN         NaN   74.000000   
max     100.000000  200.000000        NaN       NaN         NaN   80.000000   

            height course      state       marks  
count   101.000000     75         80  101.000000  
unique         NaN      4          6         NaN  
top            NaN     DA  Rajasthan         NaN  
freq           NaN     22         20         NaN  
mean    161.683168    NaN        NaN   80.366337  
std       7.342930    NaN        NaN   11.358453  
min     150.000000    NaN        NaN   60.000000  
25%     155.000000    NaN        NaN   70.000000  
50%     162.000000    NaN        NaN   82.000000  
75%     167.000000    NaN        NaN   91.000000  
max     175.000000    NaN        NaN   98.000000

In [83]:
df.drop(['id','weight'],axis=1).describe()

Unnamed: 0      height       marks
count  101.000000  101.000000  101.000000
mean    50.000000  161.683168   80.366337
std     29.300171    7.342930   11.358453
min      0.000000  150.000000   60.000000
25%     25.000000  155.000000   70.000000
50%     50.000000  162.000000   82.000000
75%     75.000000  167.000000   91.000000
max    100.000000  175.000000   98.000000

In [84]:
df.isnull().sum()  # got allthe blank values in each column.

Unnamed: 0     0
id             0
first_name     0
last_name     54
dob            0
weight         0
height         0
course        26
state         21
marks          0
dtype: int64

In [85]:
df.isnull().mean()*100

Unnamed: 0     0.000000
id             0.000000
first_name     0.000000
last_name     53.465347
dob            0.000000
weight         0.000000
height         0.000000
course        25.742574
state         20.792079
marks          0.000000
dtype: float64

In [86]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  
0            NaN     69  
1  Uttar Pradesh     82  
2      Rajasthan     84  
3      Rajasthan     63  
4  Uttar Pradesh     68

In [87]:
df['course'].unique()

array([nan, 'DA', 'Python', 'DS', 'ML'], dtype=object)

In [88]:
df['course'].nunique()

4

In [89]:
df['course'].value_counts()

course
DA        22
DS        22
ML        17
Python    14
Name: count, dtype: int64

In [90]:
df['course'].value_counts().index

Index(['DA', 'DS', 'ML', 'Python'], dtype='object', name='course')

In [91]:
df['course'].value_counts().values

array([22, 22, 17, 14], dtype=int64)

In [92]:
df['state'].unique()

array([nan, 'Uttar Pradesh', 'Rajasthan', 'Meghalaya', 'Karnataka',
       'Nagaland', 'Goa'], dtype=object)

In [93]:
df['state'].nunique()

6

In [94]:
df['state'].value_counts()

state
Rajasthan        20
Uttar Pradesh    16
Meghalaya        14
Nagaland         14
Karnataka         9
Goa               7
Name: count, dtype: int64

In [95]:
df['state'].value_counts().index

Index(['Rajasthan', 'Uttar Pradesh', 'Meghalaya', 'Nagaland', 'Karnataka',
       'Goa'],
      dtype='object', name='state')

In [96]:
df['state'].value_counts().values

array([20, 16, 14, 14,  9,  7], dtype=int64)

In [97]:
df['marks'].unique()

array([69, 82, 84, 63, 68, 86, 92, 83, 76, 98, 97, 66, 81, 85, 96, 67, 72,
       70, 79, 89, 77, 87, 91, 61, 95, 90, 94, 73, 65, 93, 64, 74, 78, 88,
       71, 60], dtype=int64)

In [98]:
df['marks'].nunique()

36

In [99]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  
0            NaN     69  
1  Uttar Pradesh     82  
2      Rajasthan     84  
3      Rajasthan     63  
4  Uttar Pradesh     68

In [100]:
df.dropna().shape

(29, 10)

In [101]:
df[['last_name']].dropna().head()

last_name
0       Kari
5  Ahluwalia
7       Mann
8      Kumer
9     Biswas

In [102]:
# df.drop(3)

In [103]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  
0            NaN     69  
1  Uttar Pradesh     82  
2      Rajasthan     84  
3      Rajasthan     63  
4  Uttar Pradesh     68

In [106]:
np.nan

nan

In [105]:
df['NewColumn'] = np.nan

In [107]:
df['NewColumn2'] = "ABC"

In [108]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  NewColumn NewColumn2  
0            NaN     69        NaN        ABC  
1  Uttar Pradesh     82        NaN        ABC  
2      Rajasthan     84        NaN        ABC  
3      Rajasthan     63        NaN        ABC  
4  Uttar Pradesh     68        NaN        ABC

In [109]:
df['CGPA'] = round(df['marks']/10,2)

In [110]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  NewColumn NewColumn2  CGPA  
0            NaN     69        NaN        ABC   6.9  
1  Uttar Pradesh     82        NaN        ABC   8.2  
2      Rajasthan     84        NaN        ABC   8.4  
3      Rajasthan     63        NaN        ABC   6.3  
4  Uttar Pradesh     68        NaN        ABC   6.8

In [115]:
df.drop(['NewColumn','NewColumn2'],inplace=True,axis=1)

In [116]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  CGPA  
0            NaN     69   6.9  
1  Uttar Pradesh     82   8.2  
2      Rajasthan     84   8.4  
3      Rajasthan     63   6.3  
4  Uttar Pradesh     68   6.8

In [117]:
# bmi = wt/h**; wt is kg, h is m

In [119]:
df['bmi'] = df['weight']/(df['height']/100)**2

In [120]:
df.head()

Unnamed: 0   id first_name last_name         dob  weight  height course  \
0           0  100    Samarth      Kari  1997-05-28      72     174    NaN   
1           1  101      Sumer       NaN  2000-06-03      62     167     DA   
2           2  102       Anay       NaN  2004-11-24      79     175    NaN   
3           3  103      Shlok       NaN  1998-12-07      62     164    NaN   
4           4  104    Anahita       NaN  1999-01-03      74     170     DA   

           state  marks  CGPA        bmi  
0            NaN     69   6.9  23.781213  
1  Uttar Pradesh     82   8.2  22.230987  
2      Rajasthan     84   8.4  25.795918  
3      Rajasthan     63   6.3  23.051755  
4  Uttar Pradesh     68   6.8  25.605536

In [121]:
rearranged_cols = ['id', 'first_name', 'last_name', 'dob', 'weight', 'bmi', 'course',
                   'state', 'marks', 'CGPA']

In [122]:
df = df[rearranged_cols]

In [124]:
df.head()

id first_name last_name         dob  weight        bmi course  \
0  100    Samarth      Kari  1997-05-28      72  23.781213    NaN   
1  101      Sumer       NaN  2000-06-03      62  22.230987     DA   
2  102       Anay       NaN  2004-11-24      79  25.795918    NaN   
3  103      Shlok       NaN  1998-12-07      62  23.051755    NaN   
4  104    Anahita       NaN  1999-01-03      74  25.605536     DA   

           state  marks  CGPA  
0            NaN     69   6.9  
1  Uttar Pradesh     82   8.2  
2      Rajasthan     84   8.4  
3      Rajasthan     63   6.3  
4  Uttar Pradesh     68   6.8